#estrategia do jogador
#1: ataque, 2: defesa, 3:o que calhar, ver o que vale mais

#redjogador1: 1
#redjogador2: 2
#redjogador3: 1

redred1: 1
redred2: 2
redred3: 1

greengreen1: 1
greengreen2: 2
greengreen3: 1

blueblue1: 1
blueblue2: 2
blueblue3: 1

