#estrategia do jogador
#1: ataque, 2: defesa, 3: o que calhar, ver o que vale mais

#redjogador1: 1
#redjogador2: 2
#redjogador3: 1

redred1: 3
redred2: 2
redred3: 3

greengreen1: 3
greengreen2: 2
greengreen3: 3

blueblue1: 3
blueblue2: 2
blueblue3: 3

